Sle 15 update
yast/patterns-yast pull request #4
Opened 2017-08-31 12:24 UTC by simotek

2017-08-31 12:26 UTC, simotek commented
Let me just chuck it through obs and make sure I didn't make a dumb mistake

2017-08-31 13:30 UTC, lslezak requested changes
`yast2-storage-ng` is actually correct; more cleanup suggested

2017-08-31 13:30 UTC, lslezak commented on package/patterns-yast.spec
>  Suggests:       ivtv
I think we can drop these `ivtv*` dependencies as well, these were added as suggestions for `yast2-tv` which has been dropped. Also the `alevt`, `kradio`, `motv`, `nxtvepg` and `v4l-tools` above were suggested for `yast2-tv`.

2017-08-31 13:30 UTC, lslezak commented on package/patterns-yast.spec
>  Suggests:       star
IIRC `star` was suggested for already dropped `yast2-backup`

2017-08-31 13:30 UTC, lslezak commented on package/patterns-yast.spec
> +Requires:       yast2-storage
This is a bit tricky, the problem is that for TW it is not available yet, but there is a separate staging project for submitting the yast2-storage-ng related packages to TW ([openSUSE:Factory:Staging:E](https://build.opensuse.org/project/show/openSUSE:Factory:Staging:E)). In SLE15 it is already included.

So for openSUSE:Factory:Staging:E or SLE15 we need `yast2-storage-ng` for normal TW still the old `yast2-storage`.

I'd use `yast2-storage-ng` here and for Factory SR we should add a comment that it must go to the Staging:E project. If this change is urgent and needs to go to TW earlier than Staging:E (which will very likely run for long time to iron all the storage-ng bugs) we need a separate SR to TW.

2017-08-31 13:30 UTC, lslezak commented on package/patterns-yast.spec
>  Suggests:       inst-source-utils
The `inst-source-utils` was suggested for `yast2-product-creator` and can be dropped. The same applies for `createrepo`.

2017-09-04 12:35 UTC, lslezak approved these changes
LGTM, thank you! 👍

2017-09-04 12:36 UTC, merged